language: rust
sudo: required
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
script:
  - ls -la /sys/class/net
  - cargo build --verbose --all
  - cargo test
